/*
 * Cooling_element_Config.h
 *
 *  Created on: Oct 15, 2021
 *      Author: msqotb
 */

#ifndef COOLING_ELEMENT_CONFIG_H_
#define COOLING_ELEMENT_CONFIG_H_

#define HEATING_COOLING_ELEMENT_LED_PIN		DIO_PIN7
#define HEATING_COOLING_ELEMENT_LED_PORT	DIO_PORTC


#define COOLING_ELEMENT_PIN		DIO_PIN5
#define COOLING_ELEMENT_PORT	DIO_PORTC


#endif /* COOLING_ELEMENT_CONFIG_H_ */
