/*
 * Heating_Cooling_Elements_Config.h
 *
 *  Created on: Oct 29, 2021
 *      Author: msqotb
 */

#ifndef HEATING_COOLING_ELEMENTS_CONFIG_H_
#define HEATING_COOLING_ELEMENTS_CONFIG_H_

#define HEATING_ELEMENT_PIN		DIO_PIN6
#define HEATING_ELEMENT_PORT	DIO_PORTC


#define COOLING_ELEMENT_PIN		DIO_PIN5
#define COOLING_ELEMENT_PORT	DIO_PORTC

#define HEATING_COOLING_ELEMENT_LED_PIN		DIO_PIN7
#define HEATING_COOLING_ELEMENT_LED_PORT	DIO_PORTC


#endif /* HEATING_COOLING_ELEMENTS_CONFIG_H_ */
