/*
 * Seven_Segment_Config.h
 *
 *  Created on: Oct 13, 2021
 *      Author: msqotb
 */

#ifndef SEVEN_SEGMENT_CONFIG_H_
#define SEVEN_SEGMENT_CONFIG_H_

#define SEVEN_SEGMENT_ENABLE2_PIN	DIO_PIN1
#define SEVEN_SEGMENT_ENABLE1_PIN	DIO_PIN0

#define SEVEN_SEGMENT_ENABLE_PORT	DIO_PORTB

/*  SEVEN_SEGMENT_DATA_PINS_NIPPLE
 * 1-MOST_NIPPLE
 * 2-LEAST_NIPPLE*/
#define SEVEN_SEGMENT_DATA_PINS_NIPPLE		MOST_NIPPLE
#define SEVEN_SEGMENT_DATA_PORT				DIO_PORTA




#endif /* SEVEN_SEGMENT_CONFIG_H_ */
