/*
 * TIMER1_Config.h
 *
 *  Created on: Sep 25, 2021
 *      Author: msqotb
 */

#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_

/* Timer1 Mode options:
1-TIMER1_MODE_NORMAL
2-TIMER1_MODE_PWM_PHASECORRECT_8BITS
3-TIMER1_MODE_PWM_PHASECORRECT_9BITS
4-TIMER1_MODE_PWM_PHASECORRECT_10BITS
5-TIMER1_MODE_CTC_TOP_OCR1A
6-TIMER1_MODE_PWM_FAST_8BITS
7-TIMER1_MODE_PWM_FAST_9BITS
8-TIMER1_MODE_PWM_FAST_10BITS
9-TIMER1_MODE_PWM_PHASE_FREQUENCY_CORRECT_TOP_ICR1
10-TIMER1_MODE_PWM_PHASE_FREQUENCY_CORRECT_TOP_OCR1A
11-TIMER1_MODE_PWM_PHASECORRECT_TOP_ICR1
12-TIMER1_MODE_PWM_PHASECORRECT_TOP_OCR1A
13-TIMER1_MODE_CTC_TOP_ICR1
14-TIMER1_MODE_PWM_FAST_TOP_ICR1
15-TIMER1_MODE_PWM_FAST_TOP_OCR1A */
#define TIMER1_MODE		TIMER1_MODE_CTC_TOP_ICR1

/*PRESCALER OPTIONS:
 *1-TIMER1_NO_PRESCALER
 *2-TIMER1_8_PRESCALER
 *3-TIMER1_64_PRESCALER
 *4-TIMER1_256_PRESCALER
 *5-TIMER1_1024_PRESCALER
 *6-TIMER1_EXTERNAL_SOURCE_FALLING
 *7-TIMER1_EXTERNAL_SOURCE_RISING */
#define TIMER1_PRESCALER	TIMER1_256_PRESCALER



/*OC1_PIN MODE IN CTC MODE OPTIONS:
 * 1-OC1_PIN_DISCONNECTED
 * 2-OC1_PIN_TOGGLE
 * 3-OC1_PIN_CLEAR
 * 4-OC1_PIN_SET
 * */
/*OC1_PIN MODE IN FAST_PWM MODE OPTIONS:
 * 1-OC1_PIN_DISCONNECTED
 * 2-OC1_PIN_TOGGLE				// disconnect OC1B and toggle OC1A	on Compare Match when on mode
 //(TIMER1_PWM_FAST_MODE_TOP_OCR1A)==MODE9|MODE14
 //else disconnect OC1A and OC1B
 * 3-OC1_PIN_CLEAR				//first high
 * 4-OC1_PIN_SET
 * */
/*OC1_PIN MODE IN Phase Correct and Phase and Frequency Correct  MODE OPTIONS:
 * 1-OC1_PIN_DISCONNECTED
 * 2-OC1_PIN_TOGGLE				// disconnect OC1B and toggle OC1A	on Compare Match when on mode
 //	(TIMER1_PWM_PHASECORRECT_MODE)==MODE15
 //else disconnect OC1A and OC1B
 * 3-OC1_PIN_CLEAR				//first high
 * 4-OC1_PIN_SET
 * */

#define OC1A_PIN_MODE	OC1_PIN_DISCONNECTED
#define OC1B_PIN_MODE	OC1_PIN_DISCONNECTED

typedef enum
{
	PIN_OC1A=1,
	PIN_OC1B
}PIN_OC1;


#define OC1A_PIN_NUMBER		DIO_PIN5
#define OC1A_PORT_NUMBER	DIO_PORTD

/* ICU PIN STATE
 * 1-FLOATING
 * 2-PULL_UP */

#define ICU_PIN_STATE		PULL_UP

/* ICU EDGE SELECT */
typedef enum{
	ICU_FALLING_EDGE,
	ICU_RISING_EDGE
}ICU_EDGE_SELECT;

#define TIMER1_ICU_EDGE_SELECT	ICU_FALLING_EDGE

/* ICU NOISE CANCELER
 * 1-FALSE
 * 2-TRUE */
#define ICU_NOISE_CANCELR		FALSE



#endif /* TIMER1_CONFIG_H_ */
